### ISSUE TITLE
Could you update 'http://dbtek.github.io/bootstrap-vertical-tabs/demo.html' ?

### ISSUE THREAD

**Issue by kesuzuki** [dbtek/bootstrap-vertical-tabs#11]
Hi

It's using 'vertical-text'. 
'https://github.com/dbtek/bootstrap-vertical-tabs/blob/master/demo.html'  is up to date.

**Comment by dbtek** [comment]
Demo (gh-pages branch) uses older version of bootstrap-vertical-tabs. Should be updated. For now I suffer from shortage of time. I appreciate PRs.

Thanks.
