### ISSUE TITLE
Tabs on bottom ?

### ISSUE THREAD

**Issue by mrblackus** [dbtek/bootstrap-vertical-tabs#14]
Hi !

First of all, good work ! It's a very nice library. ;)

Is there a way to have _both_ normal tabs (starting from the top of the `ul` element) and tabs that starts at the bottom, supposing `ul` has a sufficient height to contain a blank space between "top" tabs and "bottom" tabs ?

It would be really useful. I'll add more details if I found a way to do this.

Thanks in a advance.

**Comment by dbtek** [comment]
Hi @mrblackus,

With some custom css it should be possible. In my opinion, it's not a common need. However, it'd be cool if you could contribute your solution here for those might need it also.

Thanks.

**Comment by mrblackus** [comment]
Hi!

I manage to have tabs on bottom, but only by using a second `ul` element and forcing its position to bottom of the container with absolute positioning.
Not very elegant according to me but it works like a charm.

It looks like this
```html
<div class="col-xs-3" id="menu">
  <!-- required for floating -->
  <!-- Nav tabs -->
  <ul class="nav nav-tabs tabs-left" style="height: 100%;">
    <li class="active">
      <a data-toggle="tab" href="#home">Home</a>
    </li>
    <li>
      <a data-toggle="tab" href="#profile">Profile</a>
    </li>
  </ul>

  <ul class="nav nav-tabs tabs-left" style="position: absolute; bottom: 0px;">
    <li>
      <a data-toggle="tab" href="#contact">Contact</a>
    </li>
    <li>
      <a data-toggle="tab" href="#about">About</a>
    </li>
  </ul>
</div>

<div class="col-xs-9">
  <!-- Tab panes -->
  <div class="tab-content">
    <div class="tab-pane active" id="home">Home Tab.</div>
    <div class="tab-pane" id="profile">Profile Tab.</div>
    <div class="tab-pane" id="contact">Contact Tab.</div>
    <div class="tab-pane" id="about">About Tab.</div>
  </div>
</div>
```
