### ISSUE TITLE
Responsive view needed

### ISSUE THREAD

**Issue by chromonav** [dbtek/bootstrap-vertical-tabs#15]
Tabs do not stack properly when seen in mobile view.

**Comment by dbtek** [comment]
Thanks for reporting @chromonav. Responsiveness is based on `col-` classes. An optimisation for xs devices could be done however.

**Comment by dphizler** [comment]
The issue I get is that when the screen gets resized smaller, it works fine, it adapts, but when the screen is resized to bigger again, it doesn't go back to the initial state. The left tap menu is compress even though there is space again.
