### ISSUE TITLE
Feature: TypeScript Definitions

### ISSUE THREAD

**Issue by petrmanek** [dbtek/bootstrap-vertical-tabs#18]
Hello,
I'm using [TypeScript](http://www.typescriptlang.org) with this component and I didn't find any typings on the official repo. Would it be possible to create them?

Thanks in advance,
Pete.

**Comment by dbtek** [comment]
Hi @petrmanek,

I don't plan to support TypeScript. I don't know the ecosystem, however one can use a JavaScript sourced library in TypeScript environment. Did you look into that?
