### ISSUE TITLE
Gap between tab-content and nav-tabs

### ISSUE THREAD

**Issue by sandroboehme** [dbtek/bootstrap-vertical-tabs#19]
Thanks for creating this package! As far as I can see you are the only one who can offer right aligned nav-tabs with vertical text! It works quite well for me with the only exception that the gap between the tab-content and the nav-tabs is very big. I don't have much space for both and having this gap taking 50px looks bad. The reason is
 `.vertical-text.tabs-right {
    right: -50px;
}`
Do you have an other solution for that that doesn't create this big gab?

Thanks,

Sandro

**Comment by dbtek** [comment]
Hi @sandroboehme,
Sorry for the loong delay. It's great if this helps you in any way.
You can use some css overrides of course to arrange the gaps for your needs.
